task_id:"9So18Ss-bBJv2mdKpGDBq" situation_id:"upQvn8J3L_XQdcnGsqPFv" check_item:{check_item_id:"s-iyTWbcfb0nV4R3MlcCF" command:{command_id:"2ulps0PaysHqG-PaEZiFV" command_line:"progate diagnose"} command:{command_id:"MNFHkN35CgJ2-sagXOkHp" command_line:"bash ./.progate/check_puppeteer.sh"}} check_item:{check_item_id:"ybAE7wiZcYpysjqOX3hcN" command:{command_id:"WCOAvH79WXG59gMJOLTwm" command_line:"npm run test:tab"}} check_item:{check_item_id:"pWMvCp6lI8J2nqDjTDx74" command:{command_id:"dSz2JOk1D3MJdoGTuKGpC" command_line:"npm run test:conversion"}}