task_id:"oB-Su8LNzgGClbp4-AMwl" situation_id:"GRijFjYvp68hMt8BvDKcb" check_item:{check_item_id:"EBN3a5ImDPxR1I9Fh5zUi" command:{command_id:"FZIpWptbPq2zv832V7n9H" command_line:"progate diagnose"} command:{command_id:"Wg6iFvE5ig6apZOXD1V7X" command_line:"bash ./.progate/check_puppeteer.sh"}} check_item:{check_item_id:"dPbKjgbWC1JeGeDVOG7QM" command:{command_id:"7__L8FPnJN64iUUqSjNrm" command_line:"npm run test:layout"}} check_item:{check_item_id:"lxmFKREgjk-_g59OcOpPv" command:{command_id:"NYsqjf9qz2hZ1WNUG1vS7" command_line:"npm run test:sidebar"}} check_item:{check_item_id:"A4MsuWX8fRQX__blbpgJx" command:{command_id:"6miSFsxnR4hXlP10Z-To_" command_line:"npm run test:main"}}